package dsig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/beevik/etree"
)

// TestW3CC14NConformance tests the library's canonicalization against reference
// outputs generated by xmllint (libxml2). Each test case has an input XML file
// in testdata/c14n/ and expected outputs for C14N 1.0, C14N 1.1, and Exc-C14N.
//
// Note: xmllint's --c14n/--c14n11/--exc-c14n modes always include comments.
// We compare against our with-comments canonicalizers for an apples-to-apples
// comparison. Comment-stripping is tested separately in TestW3CC14NWithComments.
//
// Any divergence between our output and xmllint's output indicates a spec
// non-compliance that could be exploited for signature forgery.
func TestW3CC14NConformance(t *testing.T) {
	// Known limitations where divergence from xmllint is expected:
	// - attr_whitespace: etree does not perform XML attribute value normalization
	//   (tabs/newlines in attrs remain as &#x9;/&#xA; instead of being normalized
	//   to spaces before C14N). This is an etree parser limitation.
	knownLimitations := map[string]string{
		"attr_whitespace": "etree does not normalize tab/newline in attribute values (parser limitation)",
	}

	type c14nMethod struct {
		name   string
		ext    string // file extension for expected output
		makeC  func() Canonicalizer
	}

	// Use with-comments canonicalizers since xmllint always includes comments
	methods := []c14nMethod{
		{
			name:  "ExcC14N",
			ext:   ".exc-c14n",
			makeC: func() Canonicalizer { return MakeC14N10ExclusiveWithCommentsCanonicalizerWithPrefixList("") },
		},
		{
			name:  "C14N11",
			ext:   ".c14n11",
			makeC: func() Canonicalizer { return MakeC14N11WithCommentsCanonicalizer() },
		},
		{
			name:  "C14N10",
			ext:   ".c14n10",
			makeC: func() Canonicalizer { return MakeC14N10WithCommentsCanonicalizer() },
		},
	}

	// Find all test input files
	files, err := filepath.Glob("testdata/c14n/*.xml")
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no test XML files found in testdata/c14n/")
	}

	for _, xmlFile := range files {
		baseName := strings.TrimSuffix(filepath.Base(xmlFile), ".xml")

		for _, method := range methods {
			expectedFile := filepath.Join("testdata/c14n", baseName+method.ext)

			// Skip if no expected output file
			expectedBytes, err := os.ReadFile(expectedFile)
			if err != nil {
				continue
			}
			if len(expectedBytes) == 0 {
				continue
			}

			t.Run(baseName+"/"+method.name, func(t *testing.T) {
				if reason, ok := knownLimitations[baseName]; ok {
					t.Skipf("known limitation: %s", reason)
				}
				inputBytes, err := os.ReadFile(xmlFile)
				if err != nil {
					t.Fatal(err)
				}

				doc := etree.NewDocument()
				if err := doc.ReadFromBytes(inputBytes); err != nil {
					t.Fatalf("failed to parse input XML: %v", err)
				}

				el := doc.Root()
				if el == nil {
					t.Fatal("empty document")
				}

				c := method.makeC()
				got, err := c.Canonicalize(el)
				if err != nil {
					t.Fatalf("Canonicalize failed: %v", err)
				}

				expected := string(expectedBytes)
				actual := string(got)

				if actual != expected {
					t.Errorf("C14N output differs from xmllint reference\n"+
						"--- expected (xmllint) ---\n%s\n"+
						"--- got (goxmldsig) ---\n%s\n"+
						"--- diff ---\n%s",
						expected, actual, diffStrings(expected, actual))
				}
			})
		}
	}
}

// TestW3CC14NWithComments tests canonicalization with comments preserved.
func TestW3CC14NWithComments(t *testing.T) {
	input := `<doc>
 <text>First</text>
 <!-- comment -->
 <text>Second</text>
</doc>`

	tests := []struct {
		name           string
		makeC          func() Canonicalizer
		expectComment  bool
	}{
		{"ExcC14N/NoComments", func() Canonicalizer { return MakeC14N10ExclusiveCanonicalizerWithPrefixList("") }, false},
		{"ExcC14N/WithComments", func() Canonicalizer { return MakeC14N10ExclusiveWithCommentsCanonicalizerWithPrefixList("") }, true},
		{"C14N11/NoComments", func() Canonicalizer { return MakeC14N11Canonicalizer() }, false},
		{"C14N11/WithComments", func() Canonicalizer { return MakeC14N11WithCommentsCanonicalizer() }, true},
		{"C14N10/NoComments", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }, false},
		{"C14N10/WithComments", func() Canonicalizer { return MakeC14N10WithCommentsCanonicalizer() }, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := tt.makeC()
			out, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			hasComment := strings.Contains(string(out), "<!-- comment -->")
			if hasComment != tt.expectComment {
				t.Errorf("comment presence: got %v, want %v\noutput: %s", hasComment, tt.expectComment, string(out))
			}
		})
	}
}

// TestW3CExcC14NNamespacePushdown verifies that exclusive canonicalization
// pushes namespace declarations down to the elements that use them.
func TestW3CExcC14NNamespacePushdown(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name: "UnusedNamespaceStripped",
			input: `<a xmlns:unused="http://unused" xmlns:used="http://used"><used:b/></a>`,
			expected: `<a><used:b xmlns:used="http://used"></used:b></a>`,
		},
		{
			name: "NamespacePushedToUser",
			input: `<root xmlns:p="http://p"><a><p:b/></a></root>`,
			expected: `<root><a><p:b xmlns:p="http://p"></p:b></a></root>`,
		},
		{
			name: "DefaultNamespacePreserved",
			input: `<root xmlns="http://default"><a><b/></a></root>`,
			expected: `<root xmlns="http://default"><a><b></b></a></root>`,
		},
		{
			name: "AttributeNamespaceIncluded",
			input: `<root xmlns:a="http://a"><elem a:x="1"/></root>`,
			expected: `<root><elem xmlns:a="http://a" a:x="1"></elem></root>`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(tt.input); err != nil {
				t.Fatal(err)
			}

			c := MakeC14N10ExclusiveCanonicalizerWithPrefixList("")
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != tt.expected {
				t.Errorf("exc-c14n mismatch\nexpected: %s\ngot:      %s", tt.expected, string(got))
			}
		})
	}
}

// TestW3CC14NAttributeSorting verifies that attributes are sorted in canonical
// order: namespace declarations first (sorted by prefix), then remaining
// attributes sorted by namespace URI then local name.
func TestW3CC14NAttributeSorting(t *testing.T) {
	// From W3C C14N 1.0 spec, Section 3.3
	input := `<e5 xmlns:a="http://www.w3.org" a:attr="out" b:attr="sorted" attr2="all" attr="I'm" xmlns:b="http://www.ietf.org"/>`

	// Expected: namespace decls sorted by prefix, then attrs sorted by ns-uri then local
	tests := []struct {
		name     string
		makeC    func() Canonicalizer
		expected string
	}{
		{
			name:     "C14N10",
			makeC:    func() Canonicalizer { return MakeC14N10RecCanonicalizer() },
			expected: `<e5 xmlns:a="http://www.w3.org" xmlns:b="http://www.ietf.org" attr="I'm" attr2="all" b:attr="sorted" a:attr="out"></e5>`,
		},
		{
			name:     "C14N11",
			makeC:    func() Canonicalizer { return MakeC14N11Canonicalizer() },
			expected: `<e5 xmlns:a="http://www.w3.org" xmlns:b="http://www.ietf.org" attr="I'm" attr2="all" b:attr="sorted" a:attr="out"></e5>`,
		},
		{
			name:  "ExcC14N",
			makeC: func() Canonicalizer { return MakeC14N10ExclusiveCanonicalizerWithPrefixList("") },
			// Exc-C14N strips unused namespaces - both a: and b: are used on attrs
			expected: `<e5 xmlns:a="http://www.w3.org" xmlns:b="http://www.ietf.org" attr="I'm" attr2="all" b:attr="sorted" a:attr="out"></e5>`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := tt.makeC()
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != tt.expected {
				t.Errorf("attribute sorting mismatch\nexpected: %s\ngot:      %s", tt.expected, string(got))
			}
		})
	}
}

// TestW3CC14NEmptyElements verifies that self-closing tags are expanded to
// start-tag/end-tag pairs.
func TestW3CC14NEmptyElements(t *testing.T) {
	input := `<doc><empty/><also-empty></also-empty></doc>`
	expected := `<doc><empty></empty><also-empty></also-empty></doc>`

	methods := []struct {
		name  string
		makeC func() Canonicalizer
	}{
		{"ExcC14N", func() Canonicalizer { return MakeC14N10ExclusiveCanonicalizerWithPrefixList("") }},
		{"C14N11", func() Canonicalizer { return MakeC14N11Canonicalizer() }},
		{"C14N10", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }},
	}

	for _, m := range methods {
		t.Run(m.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := m.makeC()
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != expected {
				t.Errorf("expected: %s\ngot:      %s", expected, string(got))
			}
		})
	}
}

// TestW3CC14NSpecialCharacters verifies proper escaping of special characters
// in element content and attribute values.
func TestW3CC14NSpecialCharacters(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "AmpersandInContent",
			input:    `<doc>&amp;</doc>`,
			expected: `<doc>&amp;</doc>`,
		},
		{
			name:     "LessThanInContent",
			input:    `<doc>&lt;</doc>`,
			expected: `<doc>&lt;</doc>`,
		},
		{
			name:     "GreaterThanInContent",
			input:    `<doc>&gt;</doc>`,
			expected: `<doc>&gt;</doc>`,
		},
		{
			name:     "QuoteInAttrDoubleQuoted",
			input:    `<doc attr="he said &quot;hi&quot;"/>`,
			expected: `<doc attr="he said &quot;hi&quot;"></doc>`,
		},
		{
			name:     "AmpersandInAttr",
			input:    `<doc attr="a&amp;b"/>`,
			expected: `<doc attr="a&amp;b"></doc>`,
		},
		{
			name:     "LessThanInAttr",
			input:    `<doc attr="a&lt;b"/>`,
			expected: `<doc attr="a&lt;b"></doc>`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(tt.input); err != nil {
				t.Fatal(err)
			}

			c := MakeC14N10ExclusiveCanonicalizerWithPrefixList("")
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != tt.expected {
				t.Errorf("expected: %s\ngot:      %s", tt.expected, string(got))
			}
		})
	}
}

// TestW3CC14NNamespaceRedeclaration verifies correct handling of namespace
// prefix redeclarations across element boundaries.
func TestW3CC14NNamespaceRedeclaration(t *testing.T) {
	// When a prefix is rebound to a different URI, the new binding must appear.
	input := `<root xmlns:p="http://first"><a xmlns:p="http://second"><p:b/></a></root>`

	t.Run("C14N11", func(t *testing.T) {
		doc := etree.NewDocument()
		if err := doc.ReadFromString(input); err != nil {
			t.Fatal(err)
		}

		c := MakeC14N11Canonicalizer()
		got, err := c.Canonicalize(doc.Root())
		if err != nil {
			t.Fatal(err)
		}

		// In C14N 1.1, the redeclaration must appear on <a>
		result := string(got)
		if !strings.Contains(result, `xmlns:p="http://second"`) {
			t.Errorf("expected namespace redeclaration to appear\ngot: %s", result)
		}
	})

	t.Run("ExcC14N", func(t *testing.T) {
		doc := etree.NewDocument()
		if err := doc.ReadFromString(input); err != nil {
			t.Fatal(err)
		}

		c := MakeC14N10ExclusiveCanonicalizerWithPrefixList("")
		got, err := c.Canonicalize(doc.Root())
		if err != nil {
			t.Fatal(err)
		}

		result := string(got)
		// In exc-c14n, p: is only used on <p:b>, so the binding goes there
		if !strings.Contains(result, `<p:b xmlns:p="http://second">`) {
			t.Errorf("expected namespace on p:b element\ngot: %s", result)
		}
	})
}

// TestW3CC14NSuperfluous verifies that redundant namespace re-declarations are
// stripped in inclusive canonicalization.
func TestW3CC14NSuperfluous(t *testing.T) {
	input := `<a:foo xmlns:a="http://a">
 <a:bar xmlns:a="http://a">
  <a:baz xmlns:a="http://a"/>
 </a:bar>
</a:foo>`

	// The inner xmlns:a declarations are redundant and should be stripped.
	expected := `<a:foo xmlns:a="http://a">
 <a:bar>
  <a:baz></a:baz>
 </a:bar>
</a:foo>`

	methods := []struct {
		name  string
		makeC func() Canonicalizer
	}{
		{"C14N11", func() Canonicalizer { return MakeC14N11Canonicalizer() }},
		{"C14N10", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }},
	}

	for _, m := range methods {
		t.Run(m.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := m.makeC()
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != expected {
				t.Errorf("expected:\n%s\ngot:\n%s", expected, string(got))
			}
		})
	}
}

// TestW3CC14NStartEndTags tests the W3C C14N 1.0 spec Section 3.3 example:
// normalization of start/end tags, attribute quoting, and empty elements.
func TestW3CC14NStartEndTags(t *testing.T) {
	input := `<doc>
   <e1   />
   <e2   ></e2>
   <e3   name = "elem3"   id="elem3"   />
   <e4   name="elem4"   id="elem4"   ></e4>
   <e5 a:attr="out" b:attr="sorted" attr2="all" attr="I'm"
      xmlns:b="http://www.ietf.org"
      xmlns:a="http://www.w3.org"
      xmlns="http://example.org"/>
   <e6 xmlns="" xmlns:a="http://www.w3.org">
      <e7 xmlns="http://www.ietf.org">
         <e8 xmlns="" xmlns:a="http://www.w3.org">
            <e9 xmlns="" xmlns:a="http://www.ietf.org"/>
         </e8>
      </e7>
   </e6>
</doc>`

	// Expected C14N 1.0 output from the spec (and verified with xmllint)
	expected := `<doc>
   <e1></e1>
   <e2></e2>
   <e3 id="elem3" name="elem3"></e3>
   <e4 id="elem4" name="elem4"></e4>
   <e5 xmlns="http://example.org" xmlns:a="http://www.w3.org" xmlns:b="http://www.ietf.org" attr="I'm" attr2="all" b:attr="sorted" a:attr="out"></e5>
   <e6 xmlns:a="http://www.w3.org">
      <e7 xmlns="http://www.ietf.org">
         <e8 xmlns="">
            <e9 xmlns:a="http://www.ietf.org"></e9>
         </e8>
      </e7>
   </e6>
</doc>`

	methods := []struct {
		name     string
		makeC    func() Canonicalizer
		expected string
	}{
		{"C14N10", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }, expected},
		{"C14N11", func() Canonicalizer { return MakeC14N11Canonicalizer() }, expected},
	}

	for _, m := range methods {
		t.Run(m.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := m.makeC()
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != m.expected {
				t.Errorf("C14N output differs from spec\n"+
					"--- expected ---\n%s\n"+
					"--- got ---\n%s\n"+
					"--- diff ---\n%s",
					m.expected, string(got), diffStrings(m.expected, string(got)))
			}
		})
	}
}

// TestW3CExcC14NInclusiveNamespaces tests the InclusiveNamespaces PrefixList
// parameter of exclusive canonicalization.
func TestW3CExcC14NInclusiveNamespaces(t *testing.T) {
	// When a prefix is in the InclusiveNamespaces list, it should be treated
	// like inclusive canonicalization (inherited from ancestors).
	input := `<n0:local xmlns:n0="foo:bar" xmlns:n3="ftp://example.org">
 <n1:elem2 xmlns:n1="http://example.net" xml:lang="en">
  <n3:stuff xmlns:n3="ftp://example.org"/>
 </n1:elem2>
</n0:local>`

	tests := []struct {
		name       string
		prefixList string
		contains   []string
		notContains []string
	}{
		{
			name:       "NoPrefixes",
			prefixList: "",
			// n3 only visibly used on <n3:stuff>, so pushed down there
			contains:   []string{`<n3:stuff xmlns:n3="ftp://example.org"`},
		},
		{
			name:       "IncludeN3",
			prefixList: "n3",
			// n3 is now inclusive, so it should appear on the root
			contains:   []string{`xmlns:n3="ftp://example.org"`},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := MakeC14N10ExclusiveCanonicalizerWithPrefixList(tt.prefixList)
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			result := string(got)
			for _, s := range tt.contains {
				if !strings.Contains(result, s) {
					t.Errorf("expected output to contain %q\ngot: %s", s, result)
				}
			}
			for _, s := range tt.notContains {
				if strings.Contains(result, s) {
					t.Errorf("expected output NOT to contain %q\ngot: %s", s, result)
				}
			}
		})
	}
}

// TestW3CC14NXmlAttributes tests handling of xml: prefixed attributes
// (xml:lang, xml:space, etc.)
func TestW3CC14NXmlAttributes(t *testing.T) {
	input := `<doc xml:lang="en" xml:space="preserve">
 <p xml:lang="fr">Bonjour</p>
 <p>Hello</p>
</doc>`

	methods := []struct {
		name  string
		makeC func() Canonicalizer
	}{
		{"ExcC14N", func() Canonicalizer { return MakeC14N10ExclusiveCanonicalizerWithPrefixList("") }},
		{"C14N11", func() Canonicalizer { return MakeC14N11Canonicalizer() }},
		{"C14N10", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }},
	}

	for _, m := range methods {
		t.Run(m.name, func(t *testing.T) {
			doc := etree.NewDocument()
			if err := doc.ReadFromString(input); err != nil {
				t.Fatal(err)
			}

			c := m.makeC()
			got, err := c.Canonicalize(doc.Root())
			if err != nil {
				t.Fatal(err)
			}

			result := string(got)
			// xml:lang and xml:space should be preserved
			if !strings.Contains(result, `xml:lang="en"`) {
				t.Errorf("missing xml:lang on doc: %s", result)
			}
			if !strings.Contains(result, `xml:lang="fr"`) {
				t.Errorf("missing xml:lang on p: %s", result)
			}
			if !strings.Contains(result, `xml:space="preserve"`) {
				t.Errorf("missing xml:space: %s", result)
			}
		})
	}
}

// TestW3CC14NUnicodeContent verifies that Unicode content is preserved through
// canonicalization.
func TestW3CC14NUnicodeContent(t *testing.T) {
	input := `<doc><text>日本語テスト</text><text>Ñoño</text></doc>`

	doc := etree.NewDocument()
	if err := doc.ReadFromString(input); err != nil {
		t.Fatal(err)
	}

	c := MakeC14N10ExclusiveCanonicalizerWithPrefixList("")
	got, err := c.Canonicalize(doc.Root())
	if err != nil {
		t.Fatal(err)
	}

	result := string(got)
	if !strings.Contains(result, "日本語テスト") {
		t.Errorf("Japanese text not preserved: %s", result)
	}
	if !strings.Contains(result, "Ñoño") {
		t.Errorf("Spanish text not preserved: %s", result)
	}
}

// TestC14NIdempotency verifies that canonicalizing an already-canonical document
// produces identical output (idempotency property).
func TestC14NIdempotency(t *testing.T) {
	inputs := []string{
		`<doc><a/><b attr="val"/></doc>`,
		`<root xmlns:a="http://a" xmlns:b="http://b"><a:x b:y="z"/></root>`,
		`<doc xml:lang="en"><p>text &amp; more</p></doc>`,
		`<a xmlns="http://default"><b><c/></b></a>`,
	}

	methods := []struct {
		name  string
		makeC func() Canonicalizer
	}{
		{"ExcC14N", func() Canonicalizer { return MakeC14N10ExclusiveCanonicalizerWithPrefixList("") }},
		{"C14N11", func() Canonicalizer { return MakeC14N11Canonicalizer() }},
		{"C14N10", func() Canonicalizer { return MakeC14N10RecCanonicalizer() }},
	}

	for _, input := range inputs {
		for _, m := range methods {
			t.Run(m.name, func(t *testing.T) {
				// First pass
				doc1 := etree.NewDocument()
				if err := doc1.ReadFromString(input); err != nil {
					t.Fatal(err)
				}
				pass1, err := m.makeC().Canonicalize(doc1.Root())
				if err != nil {
					t.Fatal(err)
				}

				// Second pass: canonicalize the canonical output
				doc2 := etree.NewDocument()
				if err := doc2.ReadFromBytes(pass1); err != nil {
					t.Fatalf("failed to re-parse canonical output: %v", err)
				}
				pass2, err := m.makeC().Canonicalize(doc2.Root())
				if err != nil {
					t.Fatal(err)
				}

				if string(pass1) != string(pass2) {
					t.Errorf("C14N not idempotent\npass1: %s\npass2: %s", string(pass1), string(pass2))
				}
			})
		}
	}
}

// diffStrings produces a simple line-by-line diff for error messages.
func diffStrings(expected, got string) string {
	expLines := strings.Split(expected, "\n")
	gotLines := strings.Split(got, "\n")

	var b strings.Builder
	max := len(expLines)
	if len(gotLines) > max {
		max = len(gotLines)
	}

	for i := 0; i < max; i++ {
		var exp, g string
		if i < len(expLines) {
			exp = expLines[i]
		}
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if exp != g {
			b.WriteString("  expected: " + exp + "\n")
			b.WriteString("  got:      " + g + "\n")
		}
	}
	return b.String()
}
