on: [push, pull_request]
name: Test
permissions:
  contents: read

jobs:
  test:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.26', '1.25', '1.24', '1.23']
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./...
